version: "3"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12537165237615273615723657
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  rabbit:
    image: rabbitmq:3-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: 12537165237615273615723657
